Repository liquibase/liquibase-bigquery, pull requests merged in 2024-05, with the labels that each got.

#305 Set version in pom for release
  pom.xml
Labels: skipReleaseNotes

#295 [DAT-17450] Add unit tests
  .github/workflows/fossa_ai.yml
  pom.xml
  src/test/java/liquibase/ext/bigquery/change/BigQueryMergeColumnChangeTest.java
  src/test/java/liquibase/ext/bigquery/database/BigqueryDatabaseUnitTest.java
  src/test/java/liquibase/ext/bigquery/datatype/core/BignumericDataTypeBigQueryTest.java
  src/test/java/liquibase/ext/bigquery/datatype/core/BoolDataTypeBigQueryTest.java
  src/test/java/liquibase/ext/bigquery/datatype/core/Float64DataTypeBigQueryTest.java
  src/test/java/liquibase/ext/bigquery/datatype/core/GeographyDataTypeBigQueryTest.java
  src/test/java/liquibase/ext/bigquery/datatype/core/Int64DataTypeBigQueryTest.java
  src/test/java/liquibase/ext/bigquery/datatype/core/NumberDataTypeBigQueryTest.java
  src/test/java/liquibase/ext/bigquery/datatype/core/StringDataTypeBigQueryTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryAddColumnGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryAddForeignKeyConstraintGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryAddPrimaryKeyConstraintGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryCreateTableGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryDropForeignKeyConstraintGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryDropPrimaryKeyConstraintGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryInsertOrUpdateGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryModifyDataTypeGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryRenameTableGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryRenameViewGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQuerySetNullableGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryUpdateGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigqueryCreateDatabaseChangeLogLockTableGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigqueryDeleteGeneratorTest.java
Labels: TypeEnhancement

#313 [DAT-17502] fixed FK
  src/main/java/liquibase/ext/bigquery/snapshot/jvm/BigQueryForeignKeySnapshotGenerator.java
  src/main/java/liquibase/ext/bigquery/snapshot/jvm/BigQueryUniqueConstraintSnapshotGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryAddForeignKeyConstraintGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryCreateTableGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryDropForeignKeyConstraintGenerator.java
  src/main/resources/META-INF/services/liquibase.snapshot.SnapshotGenerator
  src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryAddForeignKeyConstraintGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryDropForeignKeyConstraintGeneratorTest.java
  src/test/resources/liquibase/harness/change/changelogs/bigquery/addForeignKey.xml
  src/test/resources/liquibase/harness/change/changelogs/bigquery/createTable.xml
  src/test/resources/liquibase/harness/change/changelogs/bigquery/dropForeignKey.xml
  src/test/resources/liquibase/harness/change/expectedSnapshot/bigquery/addForeignKey.json
  src/test/resources/liquibase/harness/change/expectedSnapshot/bigquery/createTable.json
  src/test/resources/liquibase/harness/change/expectedSnapshot/bigquery/dropForeignKey.json
  src/test/resources/liquibase/harness/change/expectedSql/bigquery/addForeignKey.sql
  src/test/resources/liquibase/harness/change/expectedSql/bigquery/addPrimaryKey.sql
  src/test/resources/liquibase/harness/change/expectedSql/bigquery/createTable.sql
  src/test/resources/liquibase/harness/change/expectedSql/bigquery/dropForeignKey.sql
  src/test/resources/liquibase/harness/change/expectedSql/bigquery/dropPrimaryKey.sql
  src/test/resources/liquibase/harness/change/expectedSql/bigquery/renameTrigger.sql
Labels: TypeEnhancement

#320 [DAT-1773] Resolved priorities for Datatypes and ModifyDatatype generator
  src/main/java/liquibase/ext/bigquery/datatype/core/BignumericDataTypeBigQuery.java
  src/main/java/liquibase/ext/bigquery/datatype/core/BoolDataTypeBigQuery.java
  src/main/java/liquibase/ext/bigquery/datatype/core/Float64DataTypeBigQuery.java
  src/main/java/liquibase/ext/bigquery/datatype/core/GeographyDataTypeBigQuery.java
  src/main/java/liquibase/ext/bigquery/datatype/core/Int64DataTypeBigQuery.java
  src/main/java/liquibase/ext/bigquery/datatype/core/NumericDataTypeBigQuery.java
  src/main/java/liquibase/ext/bigquery/datatype/core/StringDataTypeBigQuery.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryModifyDataTypeGenerator.java
  src/main/resources/META-INF/services/liquibase.datatype.LiquibaseDataType
  src/test/java/liquibase/ext/bigquery/datatype/core/NumberDataTypeBigQueryTest.java
Labels: TypeBug

#324 [Dat-17482] Code refactoring
  src/main/java/liquibase/ext/bigquery/change/BigQueryMergeColumnChange.java
  src/main/java/liquibase/ext/bigquery/database/BigQueryConnection.java
  src/main/java/liquibase/ext/bigquery/database/BigQueryDatabase.java
  src/main/java/liquibase/ext/bigquery/datatype/core/BignumericDataTypeBigQuery.java
  src/main/java/liquibase/ext/bigquery/datatype/core/BoolDataTypeBigQuery.java
  src/main/java/liquibase/ext/bigquery/datatype/core/Float64DataTypeBigQuery.java
  src/main/java/liquibase/ext/bigquery/datatype/core/GeographyDataTypeBigQuery.java
  src/main/java/liquibase/ext/bigquery/datatype/core/Int64DataTypeBigQuery.java
  src/main/java/liquibase/ext/bigquery/datatype/core/NumericDataTypeBigQuery.java
  src/main/java/liquibase/ext/bigquery/datatype/core/StringDataTypeBigQuery.java
  src/main/java/liquibase/ext/bigquery/diff/output/changelog/core/BigQueryChangedTableChangeGenerator.java
  src/main/java/liquibase/ext/bigquery/executor/BigQueryExecutor.java
  src/main/java/liquibase/ext/bigquery/snapshot/jvm/BigQueryDatasetSnapshotGenerator.java
  src/main/java/liquibase/ext/bigquery/snapshot/jvm/BigQueryForeignKeySnapshotGenerator.java
  src/main/java/liquibase/ext/bigquery/snapshot/jvm/BigQueryPrimaryKeySnapshotGenerator.java
  src/main/java/liquibase/ext/bigquery/snapshot/jvm/BigQuerySequenceSnapshotGenerator.java
  src/main/java/liquibase/ext/bigquery/snapshot/jvm/BigQueryUniqueConstraintSnapshotGenerator.java
  src/main/java/liquibase/ext/bigquery/snapshot/jvm/BigQueryViewSnapshotGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryAddColumnGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryAddForeignKeyConstraintGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryAddPrimaryKeyConstraintGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryCreateDatabaseChangeLogLockTableGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryCreateDatabaseChangeLogTableGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryCreateTableGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryDeleteGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryInsertOrUpdateGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryModifyDataTypeGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryRenameTableGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryRenameViewGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQuerySetNullableGenerator.java
  src/main/java/liquibase/ext/bigquery/sqlgenerator/BigQueryUpdateGenerator.java
  src/main/resources/META-INF/services/liquibase.database.Database
  src/main/resources/META-INF/services/liquibase.database.DatabaseConnection
  src/main/resources/META-INF/services/liquibase.executor.Executor
  src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
  src/test/groovy/liquibase/ext/bigquery/database/BigQueryDatabaseTest.groovy
  src/test/java/liquibase/ext/bigquery/change/BigQueryMergeColumnChangeTest.java
  src/test/java/liquibase/ext/bigquery/database/BigqueryDatabaseUnitTest.java
  src/test/java/liquibase/ext/bigquery/datatype/core/BignumericDataTypeBigQueryTest.java
  src/test/java/liquibase/ext/bigquery/datatype/core/BoolDataTypeBigQueryTest.java
  src/test/java/liquibase/ext/bigquery/datatype/core/Float64DataTypeBigQueryTest.java
  src/test/java/liquibase/ext/bigquery/datatype/core/GeographyDataTypeBigQueryTest.java
  src/test/java/liquibase/ext/bigquery/datatype/core/Int64DataTypeBigQueryTest.java
  src/test/java/liquibase/ext/bigquery/datatype/core/NumberDataTypeBigQueryTest.java
  src/test/java/liquibase/ext/bigquery/datatype/core/StringDataTypeBigQueryTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryAddColumnGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryAddForeignKeyConstraintGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryAddPrimaryKeyConstraintGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryCreateTableGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryInsertOrUpdateGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryModifyDataTypeGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryRenameTableGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryRenameViewGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQuerySetNullableGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigQueryUpdateGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigqueryCreateDatabaseChangeLogLockTableGeneratorTest.java
  src/test/java/liquibase/ext/bigquery/sqlgenerator/BigqueryDeleteGeneratorTest.java
Labels: TypeEnhancement
